
- id: 1
  name: "Headcrab"
  price: 35500
  image: "./assets/img/p1.jpg"
  description:"Criatura del juego Half-Life"

- id: 2
  name: "Gatitos llavero"
  price: 3000
  image: "./assets/img/p2.jpg"
  description:"LLavero de Gatitos articulados que se mueven"
